# Generated by Django 5.2.8 on 2025-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
